### ISSUE TITLE
Cant Place KSP Stock Storage Containers

### ISSUE THREAD

**Issue by Coaxgames** [linuxgurugamer/DeployableBatteries#2]
After installing this mod, i noticed that i cant place a container(Any) in the Editors, and it breaks bad (Clicking or Control+z Soft Locks Editor)

Steps to Recreate:
Installing the mod.
Place a Container Down in a editor.

Attempted Fixes:
Removed all other mods.
Fresh Save.
Fresh GameFiles And GameData Folder.

any time the mod is enabled in KSP 1.12.2 it Soft locks the editor and wont let me place a container.

**Comment by linuxgurugamer** [comment]
Please ask for support on the forums, that way other people can also help
I'll also need a copy of the log file (details in my signature on the forum)

**Comment by linuxgurugamer** [comment]
FYI, you need to install the SpaceTuxLibrary, if it isn't installed already
